<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Resources\Images\order-hub-icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
		<Content Remove="C:\Users\ramig\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Fonts\Cairo.ttf" />
		<None Remove="Resources\Fonts\Tajawal\Tajawal-Regular.ttf" />
		<None Remove="Resources\Images\order-hub-banner.png" />
		<None Remove="Resources\Images\OrderHub.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
		<PackageReference Include="HandyControls" Version="3.6.0" />
		<PackageReference Include="Hoax.WpfConverters" Version="1.0.0" />
		<PackageReference Include="InputSimulatorCore" Version="1.0.5" />
		<PackageReference Include="Material.Icons.WPF" Version="2.4.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Notification.Wpf" Version="8.0.0" />
		<PackageReference Include="Selenium.Support" Version="4.41.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.41.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="145.0.7632.11700" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Images\order-hub-banner.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Images\order-hub-icon.ico" />
		<Content Include="Resources\Images\OrderHub.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>OrderHub.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OrderHub.Application\OrderHub.Application.csproj" />
	  <ProjectReference Include="..\OrderHub.Domain\OrderHub.Domain.csproj" />
	  <ProjectReference Include="..\OrderHub.Infrastructure\OrderHub.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="response.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Cities\Edit\" />
	  <Folder Include="Features\Cities\Index\" />
	  <Folder Include="Features\WhatsappGroups\Create\" />
	  <Folder Include="Resources\Fonts\Tajawal\" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Fonts\Cairo.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Fonts\Tajawal-Regular.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Features\Suppliers\Editor\EditSupplierView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<Page Include="Properties\DesignTimeResources.xaml" Condition="'$(DesignTime)'=='true' OR ('$(SolutionPath)'!='' AND Exists('$(SolutionPath)') AND '$(BuildingInsideVisualStudio)'!='true' AND '$(BuildingInsideExpressionBlend)'!='true')">
			<Generator>MSBuild:Compile</Generator>
			<SubType>Designer</SubType>
			<ContainsDesignTimeResources>true</ContainsDesignTimeResources>
		</Page>
	</ItemGroup>

</Project>
