// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderHub.Infrastructure;

#nullable disable

namespace OrderHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308192220_Add_Order_OrderStusts")]
    partial class Add_Order_OrderStusts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OrderHub.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("street");

                    b.Property<int?>("city_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("city_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("city_id")
                        .HasDatabaseName("ix_addresses_city_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_category_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_clients_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_clients_phone_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Deliveryman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("deliveryman_city_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deliveryman_city_id");

                    b.HasKey("Id")
                        .HasName("pk_deliverymen");

                    b.HasIndex("deliveryman_city_id")
                        .HasDatabaseName("ix_deliverymen_deliveryman_city_id");

                    b.ToTable("deliverymen", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_method");

                    b.Property<int?>("DeliverymanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deliveryman_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending")
                        .HasColumnName("order_status");

                    b.Property<int?>("ShippingCarrierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shipping_carrier_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.HasIndex("DeliverymanId")
                        .HasDatabaseName("ix_orders_deliveryman_id");

                    b.HasIndex("ShippingCarrierId")
                        .HasDatabaseName("ix_orders_shipping_carrier_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("quantity");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_order_items_supplier_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_phones");

                    b.ToTable("phones", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.HasKey("Id")
                        .HasName("pk_shipping_carriers");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_shipping_carriers_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_shipping_carriers_phone_id");

                    b.ToTable("shipping_carriers", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_suppliers_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_suppliers_phone_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suppliers_id");

                    b.HasKey("ProductId", "SuppliersId")
                        .HasName("pk_product_supplier");

                    b.HasIndex("SuppliersId")
                        .HasDatabaseName("ix_product_supplier_suppliers_id");

                    b.ToTable("product_supplier", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Address", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_addresses_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.City", b =>
                {
                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("CityId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_cities_name");

                            b1.ToTable("cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId")
                                .HasConstraintName("fk_cities_cities_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_clients_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_clients_phones_phone_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId")
                                .HasConstraintName("fk_clients_clients_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Deliveryman", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("deliveryman_city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deliverymen_cities_deliveryman_city_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("DeliverymanId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("DeliverymanId");

                            b1.ToTable("deliverymen");

                            b1.WithOwner()
                                .HasForeignKey("DeliverymanId")
                                .HasConstraintName("fk_deliverymen_deliverymen_id");
                        });

                    b.Navigation("City");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients_client_id");

                    b.HasOne("OrderHub.Domain.Models.Deliveryman", "Deliveryman")
                        .WithMany()
                        .HasForeignKey("DeliverymanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_deliverymen_deliveryman_id");

                    b.HasOne("OrderHub.Domain.Models.ShippingCarrier", "ShippingCarrier")
                        .WithMany()
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_shipping_carriers_shipping_carrier_id");

                    b.Navigation("Client");

                    b.Navigation("Deliveryman");

                    b.Navigation("ShippingCarrier");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("OrderHub.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.HasOne("OrderHub.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_items_suppliers_supplier_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("unit_price");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId")
                                .HasConstraintName("fk_order_items_order_items_id");
                        });

                    b.Navigation("Supplier");

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Phone", b =>
                {
                    b.OwnsOne("OrderHub.Domain.ValueObjects.PhoneNumber", "Number", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("country_code");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("number");

                            b1.HasKey("PhoneId");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId")
                                .HasConstraintName("fk_phones_phones_id");
                        });

                    b.Navigation("Number");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("price");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_shipping_carriers_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_shipping_carriers_phones_phone_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ShippingCarrierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ShippingCarrierId");

                            b1.ToTable("shipping_carriers");

                            b1.WithOwner()
                                .HasForeignKey("ShippingCarrierId")
                                .HasConstraintName("fk_shipping_carriers_shipping_carriers_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "ShippingCost", b1 =>
                        {
                            b1.Property<int>("ShippingCarrierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("shipping_cost");

                            b1.HasKey("ShippingCarrierId");

                            b1.ToTable("shipping_carriers");

                            b1.WithOwner()
                                .HasForeignKey("ShippingCarrierId")
                                .HasConstraintName("fk_shipping_carriers_shipping_carriers_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");

                    b.Navigation("ShippingCost")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Supplier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_suppliers_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_suppliers_phones_phone_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.BusinessHours", "BusinessHours", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("CloseAt")
                                .HasColumnType("time")
                                .HasColumnName("close_at");

                            b1.Property<TimeSpan>("OpenAt")
                                .HasColumnType("time")
                                .HasColumnName("open_at");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("BusinessHours");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplier_products_product_id");

                    b.HasOne("OrderHub.Domain.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplier_suppliers_suppliers_id");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
