// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderHub.Infrastructure;

#nullable disable

namespace OrderHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829204909_FixInvoiceModelWitOrder")]
    partial class FixInvoiceModelWitOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OrderHub.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("street");

                    b.Property<int?>("city_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("city_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("city_id")
                        .HasDatabaseName("ix_addresses_city_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_category_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("location");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_clients_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_clients_phone_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.CommercialDocuments.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_phone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_number");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_vat");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_document_number");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_order_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.CommercialDocuments.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_amount");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id")
                        .HasName("pk_invoice_items");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_items_invoice_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_invoice_items_product_id");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Deliveryman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<int>("deliveryman_city_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deliveryman_city_id");

                    b.Property<int?>("whatsapp_group_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("whatsapp_group_id");

                    b.HasKey("Id")
                        .HasName("pk_deliverymen");

                    b.HasIndex("deliveryman_city_id")
                        .HasDatabaseName("ix_deliverymen_deliveryman_city_id");

                    b.HasIndex("whatsapp_group_id")
                        .HasDatabaseName("ix_deliverymen_whatsapp_group_id");

                    b.ToTable("deliverymen", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_method");

                    b.Property<int?>("DeliverymanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deliveryman_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending")
                        .HasColumnName("order_status");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("ShippingCarrierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shipping_carrier_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.HasIndex("DeliverymanId")
                        .HasDatabaseName("ix_orders_deliveryman_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_orders_payment_method_id");

                    b.HasIndex("ShippingCarrierId")
                        .HasDatabaseName("ix_orders_shipping_carrier_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderDeliveryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_method");

                    b.Property<int?>("DeliverymanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deliveryman_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<int?>("ShippingCarrierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shipping_carrier_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_order_delivery_steps");

                    b.HasIndex("DeliverymanId")
                        .HasDatabaseName("ix_order_delivery_steps_deliveryman_id");

                    b.HasIndex("ShippingCarrierId")
                        .HasDatabaseName("ix_order_delivery_steps_shipping_carrier_id");

                    b.HasIndex("OrderId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_order_delivery_steps_order_id_step_order");

                    b.ToTable("order_delivery_steps", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderEntitySequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("display_title");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_type");

                    b.Property<int>("SequenceMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_month");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<int>("SequenceYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_year");

                    b.HasKey("Id")
                        .HasName("pk_order_entity_sequences");

                    b.HasIndex("OrderId", "RecipientType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_entity_sequences_order_id_recipient_type_entity_id");

                    b.HasIndex("RecipientType", "EntityId", "SequenceYear", "SequenceMonth", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_order_entity_sequences_recipient_type_entity_id_sequence_year_sequence_month_sequence_number");

                    b.ToTable("order_entity_sequences", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("quantity");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_order_items_supplier_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_item_id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("property_id");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_order_item_properties");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_order_item_properties_property_id");

                    b.HasIndex("OrderItemId", "PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_item_properties_order_item_id_property_id");

                    b.ToTable("order_item_properties", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempt_at");

                    b.PrimitiveCollection<string>("LegacyAttachments")
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_attachments");

                    b.Property<int?>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.PrimitiveCollection<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipient_id");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_type");

                    b.Property<int?>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_outbox_messages_recipient_id");

                    b.HasIndex("OrderId", "RecipientId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_order_id_recipient_id")
                        .HasFilter("[Status] = 'Pending'");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<int>("OutboxMessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_file_name");

                    b.HasKey("Id")
                        .HasName("pk_message_attachments");

                    b.HasIndex("OutboxMessageId")
                        .HasDatabaseName("ix_message_attachments_outbox_message_id");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessageRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("outbox_message_recipients", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentMethods_Code");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_PaymentMethods_DisplayName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PaymentMethods_IsActive");

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ON_DELIVERY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "الدفع نقداً عند الاستلام",
                            DisplayName = "نقداً",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "BANK_TRANSFER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "الدفع عبر التحويل البنكي",
                            DisplayName = "تحويل بنكي",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "SUPPLIER_ACCOUNT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "الدفع على حساب المورد",
                            DisplayName = "على حساب المورد",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "SALLA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "الدفع عبر منصة سلة",
                            DisplayName = "سلة",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_phones");

                    b.ToTable("phones", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ProductProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_product_properties");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_product_properties_property_id");

                    b.HasIndex("ProductId", "PropertyId")
                        .HasDatabaseName("ix_product_properties_product_id_property_id");

                    b.ToTable("product_properties", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("property_type");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_properties_name");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.PropertyOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("property_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_property_options");

                    b.HasIndex("PropertyId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_property_options_property_id_value");

                    b.ToTable("property_options", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.HasKey("Id")
                        .HasName("pk_shipping_carriers");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_shipping_carriers_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_shipping_carriers_phone_id");

                    b.ToTable("shipping_carriers", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<int?>("address_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<int?>("phone_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_id");

                    b.Property<int?>("whatsapp_group_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("whatsapp_group_id");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("address_id")
                        .HasDatabaseName("ix_suppliers_address_id");

                    b.HasIndex("phone_id")
                        .HasDatabaseName("ix_suppliers_phone_id");

                    b.HasIndex("whatsapp_group_id")
                        .HasDatabaseName("ix_suppliers_whatsapp_group_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.WhatsappGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupLink")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("group_link");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("group_name");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_type");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_whatsapp_groups");

                    b.ToTable("whatsapp_groups", (string)null);
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Models.DocumentSequence", b =>
                {
                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_number");

                    b.HasKey("DocumentType", "Year", "Month")
                        .HasName("pk_document_sequences");

                    b.ToTable("document_sequences", (string)null);
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suppliers_id");

                    b.HasKey("ProductId", "SuppliersId")
                        .HasName("pk_product_supplier");

                    b.HasIndex("SuppliersId")
                        .HasDatabaseName("ix_product_supplier_suppliers_id");

                    b.ToTable("product_supplier", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ClientRecipient", b =>
                {
                    b.HasBaseType("OrderHub.Domain.Models.OutboxMessageRecipient");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_recipients_client_id");

                    b.ToTable("client_recipients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.DeliverymanRecipient", b =>
                {
                    b.HasBaseType("OrderHub.Domain.Models.OutboxMessageRecipient");

                    b.Property<int>("DeliveryManId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delivery_man_id");

                    b.HasIndex("DeliveryManId")
                        .HasDatabaseName("ix_deliveryman_recipients_delivery_man_id");

                    b.ToTable("deliveryman_recipients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrierRecipient", b =>
                {
                    b.HasBaseType("OrderHub.Domain.Models.OutboxMessageRecipient");

                    b.Property<int>("ShippingCarrierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shipping_carrier_id");

                    b.HasIndex("ShippingCarrierId")
                        .HasDatabaseName("ix_shippingcarrier_recipients_shipping_carrier_id");

                    b.ToTable("shippingcarrier_recipients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.SupplierRecipient", b =>
                {
                    b.HasBaseType("OrderHub.Domain.Models.OutboxMessageRecipient");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_recipients_supplier_id");

                    b.ToTable("supplier_recipients", (string)null);
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Address", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_addresses_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.City", b =>
                {
                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("CityId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_cities_name");

                            b1.ToTable("cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId")
                                .HasConstraintName("fk_cities_cities_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_clients_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_clients_phones_phone_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId")
                                .HasConstraintName("fk_clients_clients_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.CommercialDocuments.Invoice", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Order", "Order")
                        .WithOne()
                        .HasForeignKey("OrderHub.Domain.Models.CommercialDocuments.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.CommercialDocuments.InvoiceItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.CommercialDocuments.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_invoices_invoice_id");

                    b.HasOne("OrderHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_products_product_id");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Deliveryman", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("deliveryman_city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deliverymen_cities_deliveryman_city_id");

                    b.HasOne("OrderHub.Domain.Models.WhatsappGroup", "WhatsappGroup")
                        .WithMany()
                        .HasForeignKey("whatsapp_group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_deliverymen_whatsapp_groups_whatsapp_group_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("DeliverymanId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("DeliverymanId");

                            b1.ToTable("deliverymen");

                            b1.WithOwner()
                                .HasForeignKey("DeliverymanId")
                                .HasConstraintName("fk_deliverymen_deliverymen_id");
                        });

                    b.Navigation("City");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("WhatsappGroup");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients_client_id");

                    b.HasOne("OrderHub.Domain.Models.Deliveryman", "Deliveryman")
                        .WithMany()
                        .HasForeignKey("DeliverymanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_deliverymen_deliveryman_id");

                    b.HasOne("OrderHub.Domain.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_payment_methods_payment_method_id");

                    b.HasOne("OrderHub.Domain.Models.ShippingCarrier", "ShippingCarrier")
                        .WithMany()
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_shipping_carriers_shipping_carrier_id");

                    b.Navigation("Client");

                    b.Navigation("Deliveryman");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ShippingCarrier");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderDeliveryStep", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Deliveryman", "Deliveryman")
                        .WithMany()
                        .HasForeignKey("DeliverymanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_delivery_steps_deliverymen_deliveryman_id");

                    b.HasOne("OrderHub.Domain.Models.Order", "Order")
                        .WithMany("DeliverySteps")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_delivery_steps_orders_order_id");

                    b.HasOne("OrderHub.Domain.Models.ShippingCarrier", "ShippingCarrier")
                        .WithMany()
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_delivery_steps_shipping_carriers_shipping_carrier_id");

                    b.Navigation("Deliveryman");

                    b.Navigation("Order");

                    b.Navigation("ShippingCarrier");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderEntitySequence", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Order", "Order")
                        .WithMany("EntitySequences")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_entity_sequences_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("OrderHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.HasOne("OrderHub.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_items_suppliers_supplier_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("unit_price");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId")
                                .HasConstraintName("fk_order_items_order_items_id");
                        });

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItemProperty", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.OrderItem", "OrderItem")
                        .WithMany("Properties")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_properties_order_items_order_item_id");

                    b.HasOne("OrderHub.Domain.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_properties_properties_property_id");

                    b.Navigation("OrderItem");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessage", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Order", "Order")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_outbox_messages_orders_order_id");

                    b.HasOne("OrderHub.Domain.Models.OutboxMessageRecipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("fk_outbox_messages_outbox_message_recipient_recipient_id");

                    b.Navigation("Order");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessageAttachment", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.OutboxMessage", "OutboxMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_outbox_messages_outbox_message_id");

                    b.Navigation("OutboxMessage");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Phone", b =>
                {
                    b.OwnsOne("OrderHub.Domain.ValueObjects.PhoneNumber", "Number", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("country_code");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("number");

                            b1.HasKey("PhoneId");

                            b1.ToTable("phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId")
                                .HasConstraintName("fk_phones_phones_id");
                        });

                    b.Navigation("Number");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("price");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ProductProperty", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Product", "Product")
                        .WithMany("Properties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_properties_products_product_id");

                    b.HasOne("OrderHub.Domain.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_properties_properties_property_id");

                    b.Navigation("Product");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.PropertyOption", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Property", "Property")
                        .WithMany("Options")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_options_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_shipping_carriers_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_shipping_carriers_phones_phone_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("ShippingCarrierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("name");

                            b1.HasKey("ShippingCarrierId");

                            b1.ToTable("shipping_carriers");

                            b1.WithOwner()
                                .HasForeignKey("ShippingCarrierId")
                                .HasConstraintName("fk_shipping_carriers_shipping_carriers_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.Money", "ShippingCost", b1 =>
                        {
                            b1.Property<int>("ShippingCarrierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("shipping_cost");

                            b1.HasKey("ShippingCarrierId");

                            b1.ToTable("shipping_carriers");

                            b1.WithOwner()
                                .HasForeignKey("ShippingCarrierId")
                                .HasConstraintName("fk_shipping_carriers_shipping_carriers_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");

                    b.Navigation("ShippingCost")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Supplier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .HasConstraintName("fk_suppliers_addresses_address_id");

                    b.HasOne("OrderHub.Domain.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("phone_id")
                        .HasConstraintName("fk_suppliers_phones_phone_id");

                    b.HasOne("OrderHub.Domain.Models.WhatsappGroup", "WhatsappGroup")
                        .WithMany()
                        .HasForeignKey("whatsapp_group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_suppliers_whatsapp_groups_whatsapp_group_id");

                    b.OwnsOne("OrderHub.Domain.ValueObjects.EntityName", "Name", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_id");
                        });

                    b.OwnsOne("OrderHub.Domain.ValueObjects.BusinessHours", "BusinessHours", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("CloseAt")
                                .HasColumnType("time")
                                .HasColumnName("close_at");

                            b1.Property<TimeSpan>("OpenAt")
                                .HasColumnType("time")
                                .HasColumnName("open_at");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("BusinessHours");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");

                    b.Navigation("WhatsappGroup");
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplier_products_product_id");

                    b.HasOne("OrderHub.Domain.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplier_suppliers_suppliers_id");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ClientRecipient", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_recipients_clients_client_id");

                    b.HasOne("OrderHub.Domain.Models.OutboxMessageRecipient", null)
                        .WithOne()
                        .HasForeignKey("OrderHub.Domain.Models.ClientRecipient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_recipients_outbox_message_recipients_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.DeliverymanRecipient", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.Deliveryman", "DeliveryMan")
                        .WithMany()
                        .HasForeignKey("DeliveryManId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deliveryman_recipients_deliverymen_delivery_man_id");

                    b.HasOne("OrderHub.Domain.Models.OutboxMessageRecipient", null)
                        .WithOne()
                        .HasForeignKey("OrderHub.Domain.Models.DeliverymanRecipient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveryman_recipients_outbox_message_recipients_id");

                    b.Navigation("DeliveryMan");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.ShippingCarrierRecipient", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.OutboxMessageRecipient", null)
                        .WithOne()
                        .HasForeignKey("OrderHub.Domain.Models.ShippingCarrierRecipient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shippingcarrier_recipients_outbox_message_recipients_id");

                    b.HasOne("OrderHub.Domain.Models.ShippingCarrier", "ShippingCarrier")
                        .WithMany()
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shippingcarrier_recipients_shipping_carriers_shipping_carrier_id");

                    b.Navigation("ShippingCarrier");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.SupplierRecipient", b =>
                {
                    b.HasOne("OrderHub.Domain.Models.OutboxMessageRecipient", null)
                        .WithOne()
                        .HasForeignKey("OrderHub.Domain.Models.SupplierRecipient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_recipients_outbox_message_recipients_id");

                    b.HasOne("OrderHub.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_recipients_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.CommercialDocuments.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Order", b =>
                {
                    b.Navigation("DeliverySteps");

                    b.Navigation("EntitySequences");

                    b.Navigation("OrderItems");

                    b.Navigation("OutboxMessages");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OrderItem", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.OutboxMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Property", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
